name: zupay_ecom
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.5.0
  http: ^0.13.4
  provider: ^6.0.2
  google_fonts: ^2.3.2
  flutter_svg: ^1.0.3
  google_nav_bar: ^5.0.6
  line_icons: ^2.0.1
  fluttertoast: ^8.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
